services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    networks:
      - default

  backend:
    build: .
    container_name: backend
    ports:
      - "8085:8085"
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  default:
    name: photo_booth_network