# Use an official Python image as the base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the setup files into the container
COPY *.py requirements-setup.txt ./

# Install dependencies from the requirements file
RUN pip install --no-cache-dir -r requirements-setup.txt

# Define the default command to run the setup script with --setup argument
CMD ["python", "setup.py", "--setup"]
